### ISSUE TITLE
record/replay doesnt work

### ISSUE THREAD

**Issue by ahojjati** [nviennot/linux-2.6-scribe#3]
running: record date  
result:
File "context.pxi", line 264, in scribe.Context.**init**(src/scribe/scribe.c:6163)

**Comment by nviennot** [comment]
Try this vmware VM: http://velvetpulse.s3.amazonaws.com/vm/scribe-ubuntu-1204.tar.bz2
login is root/root

**Comment by ahojjati** [comment]
Same issue still.

**Comment by ahojjati** [comment]
steps to compile:
1. going to linux-2.6-scribe
    1.running make menuconfig
    2.running make 
    3.running make install
2. going to libscribe/build
   1.running cmake ..
   2.running make install
   3.going to py-scribe
   1. running python setup.py install

**Comment by nviennot** [comment]
I just ran the VM, things work fine.
Come check it out: `ssh 7ur0ESRh390IVgejAjUlfd8Gp@ny1.tmate.io`
