### ISSUE TITLE
booting to kernel 2.6.35 fails

### ISSUE THREAD

**Issue by ahojjati** [nviennot/linux-2.6-scribe#4]
booting to the kernel 2.6.35 results in:
ALERT! /dev/disk/by-uuid/.... does not exist.

p.s editing the kernel and replacing the uuid by /dev/sda1 doen't fix the issue.

**Comment by nviennot** [comment]
I tried the VM, and it works out of the box. Not sure how to fix.

**Comment by ahojjati** [comment]
What is your VM setup?

**Comment by nviennot** [comment]
Here's what I did:
1) download http://velvetpulse.s3.amazonaws.com/vm/scribe-ubuntu-1204.tar.bz2
2) untar
3) open the VM with vmware
4) start the VM
5) login with root/root

**Comment by ahojjati** [comment]
Ok problem is solved. Issue is with VirtualBox. you MUST use VMware to get it working.
